name: tropical
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=24.2.0
  - aws-c-auth=0.7.16
  - aws-c-cal=0.6.10
  - aws-c-common=0.9.14
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.6
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.2
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.3
  - aws-sdk-cpp=1.11.267
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.5
  - bokeh=3.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.23.0
  - cdsapi=0.7.5
  - certifi=2025.4.26
  - cffi=1.17.1
  - cfgrib=0.9.14.1
  - click=8.1.7
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - datapi=0.4.0
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.8.0
  - eccodes=2.35.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - findlibs=0.0.5
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freeglut=3.4.0
  - freetype=2.12.1
  - fsspec=2025.2.0
  - geos=3.12.1
  - gflags=2.2.2
  - glog=0.7.1
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.13.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - importlib-resources=6.4.0
  - importlib_metadata=8.6.1
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - isoduration=20.11.0
  - jasper=4.2.4
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.7
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgl=1.7.0
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.22.0
  - libgoogle-cloud-storage=2.22.0
  - libgpg-error=1.51
  - libgrpc=1.62.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.57.0
  - libnl=3.11.0
  - libopenblas=0.3.27
  - libparquet=15.0.2
  - libpciaccess=0.18
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=256.9
  - libthrift=0.19.0
  - libtiff=4.3.0
  - libudev1=257.3
  - libutf8proc=2.8.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.2.13
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.3
  - markupsafe=3.0.2
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.1
  - msgpack-python=1.1.0
  - multiurl=0.3.5
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.4.0
  - openssl=3.5.0
  - orc=2.0.0
  - overrides=7.7.0
  - packaging=24.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - proj=9.3.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.9.19
  - python-eccodes=1.5.1
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - rdma-core=55.0
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.36.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - s2n=1.4.8
  - send2trash=1.8.3
  - setuptools=68.2.2
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.3
  - tblib=3.0.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.12
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - types-python-dateutil=2.9.0.20241206
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - ucx=1.15.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.41.2
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxxf86vm=1.1.5
  - xorg-xorgproto=2024.1
  - xyzservices=2025.1.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - cftime==1.6.3
      - charset-normalizer==3.3.2
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cmocean==4.0.3
      - et-xmlfile==1.1.0
      - geopandas==1.0.1
      - idna==3.7
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - matplotlib==3.8.4
      - metpy==1.6.1
      - netcdf4==1.6.5
      - openpyxl==3.1.2
      - pandas==2.2.2
      - patsy==0.5.6
      - pillow==10.3.0
      - pint==0.23
      - platformdirs==4.2.0
      - pooch==1.8.1
      - pyogrio==0.10.0
      - python-dateutil==2.9.0.post0
      - rasterio==1.4.3
      - requests==2.31.0
      - rioxarray==0.15.0
      - scikit-learn==1.4.2
      - scipy==1.13.0
      - seaborn==0.13.2
      - statsmodels==0.14.2
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - traitlets==5.14.2
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - wget==3.2
      - xarray==2024.3.0
      - zipp==3.21.0

